automation cli
kmdlogic/kmd-logic-gateway-automation pull request #10
Opened 2020-10-06 13:14 UTC by Araballi

2020-10-06 13:22 UTC, rosieks commented on .github/workflows/cliAuto-ci.yml
> +name: Automation Liblibrary CI/CD
Suppose to be _Library_?

2020-10-06 14:03 UTC, Araballi commented on .github/workflows/cliAuto-ci.yml
> +name: Automation Liblibrary CI/CD
Fixed

2020-10-07 04:49 UTC, NakulSeerpu commented
LGTM

2020-10-07 11:26 UTC, NakulSeerpu approved these changes

2020-10-07 11:31 UTC, jaceks2106 requested changes
Generally LGTM with suggestion

2020-10-07 12:25 UTC, jaceks2106 approved these changes

2020-10-07 12:41 UTC, merged